---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
     update_cache: yes

  - name: install apache2 package
    dnf:
      name: apache2
      state: latest

  - name: add php support for apache
    dnf:
      name: libapache2-mod-php 
      state: latest
